<div class="alert alert-block alert-danger">
<b> Name: Muhammad Mohsin Ahmad
<b>
</div>

<div class="alert alert-block alert-warning">
Import <b>Libraries<b>
</div>

In [17]:
import pandas as pd

<div class="alert alert-block alert-info">
<b>1. Data Gathering<b>
</div>

<div class="alert alert-block alert-info">
 <b>2. Data Loading<b>
</div>

In [18]:
df = pd.read_csv("car_sales_data.csv")
df

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
0,Ford,Fiesta,1.0,Petrol,2002,127300,3074
1,Porsche,718 Cayman,4.0,Petrol,2016,57850,49704
2,Ford,Mondeo,1.6,Diesel,2014,39190,24072
3,Toyota,RAV4,1.8,Hybrid,1988,210814,1705
4,VW,Polo,1.0,Petrol,2006,127869,4101
...,...,...,...,...,...,...,...
49995,BMW,M5,5.0,Petrol,2018,28664,113006
49996,Toyota,Prius,1.8,Hybrid,2003,105120,9430
49997,Ford,Mondeo,1.6,Diesel,2022,4030,49852
49998,Ford,Focus,1.0,Diesel,2016,26468,23630
49999,VW,Golf,1.4,Diesel,2012,109300,10400

<div class="alert alert-block alert-info">
<b>3. Data Exploration<b>
</div>

In [19]:
# Show first 5 rows
df.head()

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
0,Ford,Fiesta,1.0,Petrol,2002,127300,3074
1,Porsche,718 Cayman,4.0,Petrol,2016,57850,49704
2,Ford,Mondeo,1.6,Diesel,2014,39190,24072
3,Toyota,RAV4,1.8,Hybrid,1988,210814,1705
4,VW,Polo,1.0,Petrol,2006,127869,4101

In [20]:
# Print column names
print(df.columns)

Index(['Manufacturer', 'Model', 'Engine size', 'Fuel type',
       'Year of manufacture', 'Mileage', 'Price'],
      dtype='object')

In [27]:
df.duplicated().sum()

np.int64(12)

In [26]:
print(df.shape)

(50000, 7)

In [21]:
# Basic info about dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         50000 non-null  object
 1   Model                50000 non-null  object
 2   Engine size          50000 non-null  float64
 3   Fuel type            50000 non-null  object
 4   Year of manufacture  50000 non-null  int64
 5   Mileage              50000 non-null  int64
 6   Price                50000 non-null  int64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.7+ MB
None

In [22]:
# Statistical summary
print(df.describe())

        Engine size  Year of manufacture        Mileage          Price
count  50000.000000         50000.000000   50000.000000   50000.000000
mean       1.773058          2004.209440  112497.320700   13828.903160
std        0.734108             9.645965   71632.515602   16416.681336
min        1.000000          1984.000000     630.000000      76.000000
25%        1.400000          1996.000000   54352.250000    3060.750000
50%        1.600000          2004.000000  100987.500000    7971.500000
75%        2.000000          2012.000000  158601.000000   19026.500000
max        5.000000          2022.000000  453537.000000  168081.000000

In [23]:
# Unique value for Manufacturer Column

df["Manufacturer"].unique()

array(['Ford', 'Porsche', 'Toyota', 'VW', 'BMW'], dtype=object)

In [24]:
# Unique value for every column   
df.nunique()

Manufacturer               5
Model                     15
Engine size               14
Fuel type                  3
Year of manufacture       39
Mileage                44971
Price                  25045
dtype: int64

In [25]:
# Check for null values
print(df.isnull().sum())

Manufacturer           0
Model                  0
Engine size            0
Fuel type              0
Year of manufacture    0
Mileage                0
Price                  0
dtype: int64